<?xml version ="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE prediccion[
<!ELEMENT prediccion (datosPoblacion, prediccionTiempo)>
    <!ELEMENT datosPoblacion (nombrePoblacion, nombreProvincia, nombreLocalidad)>
        <!ELEMENT nombrePoblacion (#PCDATA)>
        <!ELEMENT nombreProvincia (#PCDATA)>
        <!ELEMENT nombreLocalidad (#PCDATA)>
    <!ELEMENT prediccionTiempo (fecha, temperaturaMaxima, temperaturaMinima, probabilidadLluvia)>
        <!ELEMENT fecha (#PCDATA)>
        <!ELEMENT temperaturaMaxima (#PCDATA)>
        <!ELEMENT temperaturaMinima (#PCDATA)>
        <!ELEMENT probabilidadLluvia (#PCDATA)>
]>
<prediccion>
    <datosPoblacion>
        <nombrePoblacion>Alfajor</nombrePoblacion>
        <nombreProvincia>Mar de plata</nombreProvincia>
        <nombreLocalidad>Boca</nombreLocalidad>
    </datosPoblacion>    
    <prediccionTiempo>
        <fecha>02-05-2022</fecha>
        <temperaturaMaxima>24ยบ</temperaturaMaxima>
        <temperaturaMinima>16ยบ</temperaturaMinima>
        <probabilidadLluvia>50%</probabilidadLluvia>
    </prediccionTiempo>
    <prediccionTiempo>
        <fecha>03-05-2022</fecha>
        <temperaturaMaxima>26ยบ</temperaturaMaxima>
        <temperaturaMinima>18ยบ</temperaturaMinima>
        <probabilidadLluvia>12%</probabilidadLluvia>
    </prediccionTiempo>
</prediccion>